# Configurare aplicatie KinetoLive
spring.application.name=KinetoLive

# Port backend
server.port=8080

# Configurare PostgreSQL local
spring.datasource.url=jdbc:postgresql://localhost:5432/kinetolive_db
spring.datasource.username=kinetolive_user
spring.datasource.password=kinetolive_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurare JPA si Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configurare Swagger/OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha


# Configurare microserviciu Python ML
kinetolive.ml-service.base-url=http://localhost:8000

# Permite backend-ului sa fie accesat din reteaua locala
server.address=0.0.0.0

# Configurare JWT pentru autentificarea doctorilor
kinetolive.jwt.secret=KinetoLiveJwtSecretForDoctorAuthentication2026LocalPrototype
kinetolive.jwt.expiration-minutes=720
